### ISSUE TITLE
no shape in pdf output

### ISSUE THREAD

**Issue by tiemes** [cybathlon-at-school/planvec#23]
[0_Marco_2021-02-05_14-43-08-656771_output.pdf](https://github.com/cybathlon-at-school/planvec/files/5956731/0_Marco_2021-02-05_14-43-08-656771_output.pdf)

Matthia had this issue after several others worked well before. He was still seeing the outline in the UX, the pdf export however looked like the one attached. He then restarted everything and it worked as usual again.  He thought it might have to do something with lines drawn over the green lines.

**Comment by matthaeusheer** [comment]
Ich glaaaaube ich weiss warum das passiert. Ich glaube aber auch ich weiss gerade nicht so, wie das behoben werden könnte. Liegt daran, dass im Processing Thread eventuell noch ein Bild in der Queue hängt, was nacher genommen wird. Falls hier kein Shape extrahiert worden konnte, kann das da oben tatsächlich passieren. Wenn aber das Scanning von der Zeichnung stabil ist, sollte das eigentlich nie zu einem Problem werden. Ansonsten einfach löschen. Vielleicht kommt mir noch eine Lösung in den Sinn, wie man das umgehen könnte.
