### ISSUE TITLE
does not run (at all or out-of-the-box) with ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by tiemes** [cybathlon-at-school/planvec#57]
on Ubuntu 22.04 LTS, the software runs into different problems if installed according to the docu. It does not start and is not usable. It still works on 20.04 LTS.

**Comment by matthaeusheer** [comment]
Ubuntu 22.04 is supported with release **https://github.com/cybathlon-at-school/planvec/releases/tag/v0.0.8**

**Comment by tiemes** [comment]
awesome, thanks! I'll give feedback once I find time to test it.

**Comment by tiemes** [comment]
works like a charm 👍
